---
namespace: cisco
name: dnac
version: 3.3.0
readme: README.md
authors:
- Rafael Campos <rcampos@altus.cr>
- William Astorga <wastorga@altus.cr>
- Jose Bogarin <jbogarin@altus.cr>
description: Ansible Modules for Cisco DNA Center
license_file: 'LICENSE'
tags:
- cisco
- dnac
- cloud
- collection
- networking
- sdn
dependencies:
  ansible.utils: ">=2.0.0,<3.0"
repository: https://github.com/cisco-en-programmability/dnacenter-ansible
documentation: https://developer.cisco.com/docs/dna-center/#!ansible
homepage: https://github.com/cisco-en-programmability/dnacenter-ansible
issues: https://github.com/cisco-en-programmability/dnacenter-ansible/issues
